### PR TITLE
EIP-8

### PR DESCRIPTION
**Pull request by fjl**
Implements https://github.com/ethereum/EIPs/pull/49.

### CODE REVIEW

**Comment by fjl** [comment]
@ms83 I can't get full app tests to pass (see Travis output in this PR). Do they pass for you?

**Comment by panpilkarz** [comment]
Yes. https://travis-ci.org/ethereum/pydevp2p/pull_requests

**Comment by fjl** [comment]
Alright. We've decided to go forward with EIP-8, so this PR is now open for review.

I still can't get the full app tests to pass. I tried cherry picking the first few commits from https://github.com/ethereum/pydevp2p/pull/35 but it didn't help.

**Comment by fjl** [comment]
Rebased again. Tests work now (thanks @ulope).

You can test the RLPx handshake changes against go-ethereum by doing:

``` text
... start your node...

git clone --branch develop https://github.com/ethereum/go-ethereum
cd go-ethereum
make
RLPX_EIP8=yes ./build/bin/geth --bootnodes <your enode URL>
```

**Comment by heikoheiko** [comment]
@fjl awesome! thank you!

**Comment by konradkonrad** [comment]
oops...?

**Review by St0nersdash — APPROVED** [review]

**Review by ASISBusiness — COMMENTED** [review]
Working

**Comment by rockinem** [comment]
What's liberal even mean

**Pull request merged**
